name: Test Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'installer/**'
      - 'modules/**'
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/test.yaml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v15
      with:
        name: ${{ vars.CACHIX_CACHE_NAME || 'vybovaly' }}
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: ${{ secrets.CACHIX_AUTH_TOKEN == '' }}

    - name: Build artifacts
      run: |
        echo "Building Vybovaly artifacts for testing..."

        # Build using the release-artifacts package for consistency
        nix build .#release-artifacts

    - name: Verify checksums
      run: |
        cd result

        # Verify checksums
        sha256sum -c checksums.txt

        # Check required files exist
        test -f bzImage
        test -f initrd
        test -f netboot.ipxe

        # Validate iPXE scripts
        head -1 netboot.ipxe | grep -q "^#!ipxe"

        echo "✅ All artifacts verified successfully"

    - name: Run flake checks
      run: |
        echo "Running flake checks..."
        nix flake check

    - name: Test VM environment build
      run: |
        echo "Testing VM test environment..."
        nix build .#vm-test-env --no-link
